### ISSUE TITLE
Tracksuite assumes the Git default branch is 'master'

### ISSUE THREAD

**Issue by oiffrig** [ecmwf/tracksuite#6]
### What happened?

The repository created by `tracksuite-init` honours the `init.defaultbranch` option in the Git configuration, meaning that the default branch may have any name depending on configuration (most likely, `main`). However, `tracksuite.GitDeployment.check_sync_local_remote` assumes the branch is called `master`, hence failing because the branch is not found.

### What are the steps to reproduce the bug?

```
git config --global init.defaultbranch main
tracksuite-init -t /path/to/target
```

Then, try deploying a suite

### Version

develop

### Platform (OS and architecture)

Linux

**Comment by corentincarton** [comment]
Should be solved in https://github.com/ecmwf/tracksuite/commit/90b738124f2c08e051707477ce58b25dfbc6bf9a

Can you give it another  try?

**Comment by oiffrig** [comment]
Yep, that works!
